sonar.projectKey=aovalenciar_SimpleBank
sonar.organization=aovalenciar

sonar.sources=InterviewBank
sonar.tests=InterviewBankTests

sonar.coverageReportPaths=sonarqube-generic-coverage.xml

sonar.exclusions=**/*.xcodeproj/**,**/DerivedData/**,**/Scripts/**
sonar.test.inclusions=InterviewBankTests/**/*.swift